export const data = [
  {
    id: 1,
    img: "assets/images/Barbie.jpg",
    title: "Barbie (2023)",
    year: "2023",
    nation: "US",
    info:"Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    clip:"https://www.youtube.com/embed/8zIf0XvoL9Y"
  },
  {
    id: 2,
    img: "assets/images/Expend4bles.jpg",
    title: "Expend4bles (2023)",
    year: "2023",
    nation: "US",
    info:"Armed with every weapon they can get their hands on and the skills to use them, The Expendables are the world’s last line of defense and the team that gets called when all other options are off the table. But new team members with new styles and tactics are going to give “new blood” a whole new meaning.",
    clip:"https://www.youtube.com/embed/DhlaBO-SwVE"
  },

  {
    id: 3,
   img: "assets/images/3jpg.jpg",
    title: "Oppenheimer(2023)",
    year: "2023",
    nation: "US",
    info: "Oppenheimer is a true masterclass in how to build extreme tension and suspense through fast, detailed dialogue, an insanely powerful sound production, and an equally explosive score from Ludwig Göransson. Words cannot fully describe Hoyte van Hoytema's gorgeous cinematography.",
    clip: "https://www.youtube.com/embed/bK6ldnjE3Y0",
  },

  {
    id: 4,
   img: "assets/images/Loki.jpg",
    title: "Loki (2021)",
    year: "2021",
    nation: "US",
    info: "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
    clip: "https://www.youtube.com/embed/G4JuopziR3Q",
  },

  {
    id: 5,
    img: "assets/images/RickandMorty.jpg",
    title: "Rick and Morty (2013)",
    year: "2013",
    nation: "US",
    info: "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    clip: "https://www.youtube.com/embed/WNhH00OIPP0",
  },

  {
    id: 6,
    img: "assets/images/TheBurial.jpg",
    title: "The Burial (2023)",
    year: "2023",
    nation: "US",
    info: "Inspired by true events, when a handshake deal goes sour, funeral home owner Jeremiah O'Keefe enlists charismatic, smooth-talking attorney Willie E. Gary to save his family business. Tempers flare and laughter ensues as the unlikely pair bond while exposing corporate corruption and racial injustice in this inspirational, triumphant story.",
    clip: "https://www.youtube.com/embed/ZOhIdaufd3Q",
  },

  {
    id: 7,
   img: "assets/images/TheConference.jpg",
    title: "The Conference (2023)",
    year: "2023",
    nation: "US",
    info: "A team-building conference for municipal employees turns into a nightmare when accusations of corruption begin to circulate and plague the work environment. At the same time, a mysterious figure begins murdering the participants.",
    clip: "https://www.youtube.com/embed/52fRAzmjJoQ",
  },
  {
    id: 8,
   img: "assets/images/TheEqualizer3.jpg",
    title: "The Equalizer 3 (2023)",
    year: "2023",
    nation: "US",
    info: "Robert McCall finds himself at home in Southern Italy but he discovers his friends are under the control of local crime bosses. As events turn deadly, McCall knows what he has to do: become his friends' protector by taking on the mafia.",
    clip: "https://www.youtube.com/embed/19ikl8vy4zs",
  },
  {
    id: 9,
   img: "assets/images/TheNunII.jpg",
    title: "The Nun II (2023)",
    year: "2023",
    nation: "US",
    info: "N Golo Kanté (born 29 March 1991) is a French professional footballer who plays as a central midfielder for Premier League club Chelsea and the France national team. Kanté is widely praised for his work rate and defensive acumen.",
    clip: "https://www.youtube.com/embed/QF-oyCwaArU",
  },
  {
    id: 10,
   img: "assets/images/fastx.jpg",
    title: "Fast X (2023)",
    year: "2023",
    nation: "US",
    info: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
    clip: "https://www.youtube.com/embed/32RAq6JzY-w",
  },
  {
    id: 11,
   img: "assets/images/spider.jpg",
    title: "Spider-Man (2019)",
    year: "2019",
    nation: "US",
    info: "Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.",
    clip: "https://www.youtube.com/embed/DYYtuKyMtY8",
  },
  {
    id: 12,
   img: "assets/images/gijoe.jpg",
    title: "G.I.Joe: Retaliation (2013)",
    year: "2013",
    nation: "US",
    info: "Framed for crimes against the country, the G.I. Joe team is terminated by Presidential order. This forces the G.I. Joes into not only fighting their mortal enemy Cobra; they are forced to contend with threats from within the government that jeopardize their very existence.",
    clip: "https://www.youtube.com/embed/2vAo4rJPqQ4",
  },
];
